# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nix-fast-build = {
    pname = "nix-fast-build";
    version = "aab5e31486633d1603e5469c097cf2aafea33ac6";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "nix-fast-build";
      rev = "aab5e31486633d1603e5469c097cf2aafea33ac6";
      fetchSubmodules = false;
      sha256 = "sha256-sc/NZIHkRhgyAzK8Xn6G++vGrl/Uf7QHh+J5fnZ/o4s=";
    };
    date = "2026-09-28";
  };
}
