# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nix-fast-build = {
    pname = "nix-fast-build";
    version = "d252e56a121a6090d8396d3b601c64aca3d71f8f";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "nix-fast-build";
      rev = "d252e56a121a6090d8396d3b601c64aca3d71f8f";
      fetchSubmodules = false;
      sha256 = "sha256-L4HfADUq4Imq1LnvmjBPFBEAZAIKD9Pnj6ExRkVqHC4=";
    };
    date = "2026-09-20";
  };
}
