# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  duckai = {
    pname = "duckai";
    version = "b48de2db52c99408e0133807ddca284f70ec5f95";
    src = fetchgit {
      url = "https://github.com/jairo-litman/duckai.git";
      rev = "b48de2db52c99408e0133807ddca284f70ec5f95";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DBXDbfh6bRNxbGFCiBz/HHq5VaozN+PG/eSQj2fqpvg=";
    };
    date = "2026-06-20";
  };
  nix-fast-build = {
    pname = "nix-fast-build";
    version = "6b8e373d9744c4e60e7b010649ae61c3645a8107";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "nix-fast-build";
      rev = "6b8e373d9744c4e60e7b010649ae61c3645a8107";
      fetchSubmodules = false;
      sha256 = "sha256-dfrtmjTPICHuw4hHHqwJjSVABZ1XI1TvHnpT697vxN8=";
    };
    date = "2026-09-05";
  };
}
