[rofi_catppuccin]
src.git = "https://github.com/catppuccin/rofi.git"
fetch.github = "catppuccin/rofi"

[rofi-bluetooth]
src.git = "https://github.com/nickclyde/rofi-bluetooth.git"
fetch.github = "nickclyde/rofi-bluetooth"

[prismlauncher_catppuccin]
src.git = "https://github.com/catppuccin/prismlauncher.git"
fetch.github = "catppuccin/prismlauncher"

[obs_catppuccin]
src.git = "https://github.com/catppuccin/obs.git"
fetch.github = "catppuccin/obs"

[nix-fast-build]
src.git = "https://github.com/Mic92/nix-fast-build.git"
fetch.github = "Mic92/nix-fast-build"

[firefox-gnome-theme]
src.github = "rafaelmardojai/firefox-gnome-theme"
fetch.github = "rafaelmardojai/firefox-gnome-theme"

# TODO: Set this to update automatically.
[filen]
src.manual = "latest"
fetch.url = "https://cdn.filen.io/desktop/release/filen_x86_64.AppImage"

[wickedwizard_picture]
src.manual = "latest"
fetch.url = "https://i.pinimg.com/736x/d9/f5/81/d9f58165f05408c80043abebdd62eea5.jpg"

[catppuccin_zsh_syntax_highlighting]
src.git = "https://github.com/catppuccin/zsh-syntax-highlighting.git"
fetch.github = "catppuccin/zsh-syntax-highlighting"

[calibre_catppuccin]
src.git = "https://github.com/catppuccin/calibre.git"
fetch.github = "catppuccin/calibre"

[joplin_catppuccin]
src.git = "https://github.com/catppuccin/joplin.git"
fetch.github = "catppuccin/joplin"

[eza_themes]
src.git = "https://github.com/eza-community/eza-themes.git"
fetch.github = "eza-community/eza-themes"
