{ config, ... }: {
  containers.caddy.services.freellmapi = "freellmapi:3001";

  secretspec.config = {
    profiles.selfhosted = {
      # Should be autogenerated, but we manually set it
      # for a smoother migration (agenix -> secretspec)
      ENCRYPTION_KEY.description = "Encryption key for freellmapi";
      FREEAPI_BLOCK_PRIVATE_PROVIDER_URLS = {
        description = "Whether to tell freellmapi to block private provider URLs";
        required = false;
        default = "true";
      };
    };
    scopes.freellmapi.secrets = [
      "ENCRYPTION_KEY"
      "FREEAPI_BLOCK_PRIVATE_PROVIDER_URLS"
    ];
  };

  programs.quadlets.quadlets."freellmapi.container" = {
    __options.networkNameAlias = false;
    Container = {
      ContainerName = "freellmapi";
      Image = "ghcr.io/tashfeenahmed/freellmapi:latest";
      Network = "systemd-caddy.network";
      Volume = [
        ":/app/server/data"
      ];
      EnvironmentFile = config.secretspec.secrets.scopes.freellmapi.path;

      HealthCmd = ''
        node -e "fetch('http://127.0.0.1:3001/api/ping').then((res)=>{if(!res.ok)process.exit(1)}).catch(()=>process.exit(1))"
      '';
      HealthInterval = "30s";
      HealthTimeout = "5s";
      HealthStartPeriod = "15s";
      HealthRetries = 3;
    };
  };
}
