# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "v149.1";
    src = fetchFromGitHub {
      owner = "rafaelmardojai";
      repo = "firefox-gnome-theme";
      rev = "v149.1";
      fetchSubmodules = false;
      sha256 = "sha256-QFY6Eu0kmaWl8W76bXs5K2BVtTh+Md+1rGba1WiTYxU=";
    };
  };
  nix-fast-build = {
    pname = "nix-fast-build";
    version = "49143a9692f6a97915e0b4cc6c1cc5b25d09dd27";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "nix-fast-build";
      rev = "49143a9692f6a97915e0b4cc6c1cc5b25d09dd27";
      fetchSubmodules = false;
      sha256 = "sha256-URMu3Gm2fh4lhbzkS0BlERRpK4H0xsiIRFgFY4GqcvM=";
    };
    date = "2026-08-14";
  };
  obs_catppuccin = {
    pname = "obs_catppuccin";
    version = "054a297d303a5bac4f1652a13b17d78a13201c0e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "obs";
      rev = "054a297d303a5bac4f1652a13b17d78a13201c0e";
      fetchSubmodules = false;
      sha256 = "sha256-zFg7dgxLIK3K1KpLdEgphH2JpdMwVTovr+oKiAqdLEE=";
    };
    date = "2026-06-20";
  };
  prismlauncher_catppuccin = {
    pname = "prismlauncher_catppuccin";
    version = "1ef0e745286ce32750abc3bc5d3ca8073a623b60";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "prismlauncher";
      rev = "1ef0e745286ce32750abc3bc5d3ca8073a623b60";
      fetchSubmodules = false;
      sha256 = "sha256-RN1VM29OH75GHSHgpu3HW8YSonIEnX7MZzCObJ6BwtQ=";
    };
    date = "2025-09-08";
  };
  radicale_birthday_hook = {
    pname = "radicale_birthday_hook";
    version = "535ae54ef6464b1aba825af794ecc4c4dbf3d3c3";
    src = fetchgit {
      url = "https://github.com/iBigQ/radicale-birthday-calendar.git";
      rev = "535ae54ef6464b1aba825af794ecc4c4dbf3d3c3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X/tahL01rGyc6eg1UqXhINi0mbuhwdzi4cYN8B0K+5c=";
    };
    date = "2025-02-04";
  };
  wickedwizard_picture = {
    pname = "wickedwizard_picture";
    version = "latest";
    src = fetchurl {
      url = "https://i.pinimg.com/736x/d9/f5/81/d9f58165f05408c80043abebdd62eea5.jpg";
      sha256 = "sha256-lagT6en5bMTeDsUmFFGMiFeg5O21RFUQez2Y0U8QYZU=";
    };
  };
}
