name: "Build and Push"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: fractal-next
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: cachix --version
    - run: nix-build "<nixpkgs>" -A fractal-next

