name: "Flake Update"

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build-system:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Substituters
      run: |
        sed -n '/trusted-public-keys = \[/, /];/{ /trusted-public-keys = \[/! { /];/! p } }' ./System/Common/configuration.nix | xargs > trusted-public-keys.txt
        sed -n '/substituters = \[/, /];/{ /substituters = \[/! { /];/! p } }' ./System/Common/configuration.nix | xargs >> substituters.txt

        echo "TRUSTED_PUBLIC_KEYS=$(cat trusted-public-keys.txt)" >> "$GITHUB_ENV"
        echo "SUBSTITUTERS=$(cat substituters.txt)" >> "$GITHUB_ENV"

    - name: "Install Nix"
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          trusted-public-keys = ${{ env.TRUSTED_PUBLIC_KEYS }}
          substituters = ${{ env.SUBSTITUTERS }}

    - name: "Cachix"
      uses: cachix/cachix-action@v12
      with:
        name: spearman4157
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Update Nix Flake"
      run: nix --accept-flake-config --show-trace --print-build-logs --verbose flake update

    - name: "Build Packages"
      run: bash ./nix.sh ci

    - name: "Ntfy failure notifications"
      if: failure()
      run: |
        curl \
          -H "Click: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -d "Flake Update Github Actions has failed!" \
          ${{ secrets.NTFY_URL }}

        exit 1

    - name: "Configure Git"
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: "Stage, Commit and Push"
      run: |
        git add flake.lock
        git commit -sm "chore: update flake.lock"
        git push origin master
