name: "Flake Update"

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-system:
    runs-on: ubuntu-latest
    steps:
    - uses: easimon/maximize-build-space@v10
      with:
        build-mount-path: '/nix'
        root-reserve-mb: '10240'

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Install Nix"
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: "Update Nix Flake"
      run: nix flake update --accept-flake-config

    - name: "Build Packages"
      run: nixos-rebuild build --accept-flake-config --flake .#hp-laptop

    - name: "Cachix"
      uses: cachix/cachix-action@v12
      with:
        name: spearman4157
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

