name: "Flake Update"

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  build-system:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Substituters
      run: |
        echo "TRUSTED_PUBLIC_KEYS=$(./nix.sh ci_get trusted-public-keys)" >> "$GITHUB_ENV"
        echo "SUBSTITUTERS=$(./nix.sh ci_get trusted-substituters)" >> "$GITHUB_ENV"

    - name: "Install Nix"
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          trusted-public-keys = ${{ env.TRUSTED_PUBLIC_KEYS }}
          substituters = ${{ env.SUBSTITUTERS }}

    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: "Update flake.lock and nvfetcher"
      run: |
        nix --accept-flake-config --show-trace --print-build-logs --verbose flake update 2>&1 | tee flake-update.txt
        nix develop .#ci --command bash -c nvfetcher 2>&1 | tee nvfetcher-update.txt

    - name: "Write changelog"
      id: changelog
      run: |
        echo "::set-output name=pr_title::$(echo "chore: update flake.lock & sources ($(date -I))")"
        echo "::set-output name=flake_changelog::$(grep -E "'\s\(|Updated input" flake-update.txt || echo "")"
        echo "::set-output name=sources_changelog::$(grep -E "→" nvfetcher-update.txt || echo "")"
        echo "::set-output name=date_week::$(date +%V)"

    # - name: "Build Packages"
    #   run: |
    #     nix develop .#ci --command bash -c "CACHIX_AUTH_TOKEN=${{ secrets.CACHIX_AUTH_TOKEN }} ./nix.sh ci"

    # - name: "Configure Git"
    #   run: |
    #     git config --global user.name "GitHub Actions"
    #     git config --global user.email "actions@github.com"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: ${{ steps.changelog.outputs.pr_title }}
        commit-message: ${{ steps.changelog.outputs.pr_title }}
        signoff: true
        branch: flake-update/${{ steps.changelog.outputs.date_week }}
        body: |
          Automated Pull Request for Week ${{ steps.changelog.outputs.date_week }}

          Flakes Changelog:
          ${{ steps.changelog.outputs.flake_changelog }}

          Sources Changelog:
          ${{ steps.changelog.outputs.sources_changelog }}
